version: '3'
services:
  web:
    build: .
    ports:
     - "5001:5000"
  redis:
    image: redis:latest
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"